### PR TITLE
Remove invalid topics from targetTopics on INVALID_TOPIC_EXCEPTION

### LINKED ISSUE #665: KafkaJSProtocolError: The request attempted to perform an operation on an invalid topic
Hi, we just found a weird problem about " The request attempted to perform an operation on an invalid topic".
we use dynamic topic like this:
```
function produce(type, content, response) {

  const topic = TOPIC_PREFIX + content.project + '-' + content.platform + '-' + type;
  let message = JSON.stringify(content);
  
  kafka.produce(topic, message).then(() => {
    output(response, 200, 'OK');
  }).catch(err => {
    output(response, 252, 'server error.');
  });
}
```
and when the value of _type_  contains special character, such as _type =  abc)(*&^%_ , it will throw an error like " KafkaJSProtocolError: The request attempted to perform an operation on an invalid topic".

that is all OK.

but after that , all produce operations , include the normal topic , can not work. the all throw a invalid topic error.

if we restart the server, the problem will fixed. but  if the wrong topic appear agian, and the problem will come back.

plz help us , thanks!

### PR DESCRIPTION
**Pull request by Nevon**
Fixes #665

### CODE REVIEW

File: src/cluster/index.js [hunk 1]
```diff
@@ -163,14 +163,23 @@ module.exports = class Cluster {
...
 
     const hasChanged = previousSize !== this.targetTopics.size || !this.brokerPool.metadata
 
     if (hasChanged) {
-      await this.refreshMetadata()
+      try {
+        await this.refreshMetadata()
+      } catch (e) {
+        if (e.type === 'INVALID_TOPIC_EXCEPTION') {
+          this.targetTopics = previousTopics
```
Comment (JaapRood) [inline src/cluster/index.js]: By storing the previous topics per method call, is there a possibility of us introducing a race condition here? I'm too unfamiliar with this part of the codebase whether that's something reasonable to expect or not.

If we _are_ creating a race condition here, the most simple way to mitigate in my mind is to store the previous topics on the cluster instance and use that (or a Promise of it) as a lock to only allow a single inflight call. Alternatively, we could be more careful with adding new topics to the targets list, only revert the ones for which we got the exception (which should be idempotent, so deletion of them of a Set should be without consequence).

Comment (Nevon) [reply src/cluster/index.js]: Ah, you are a learned and erudite gentleman. I didn't think about the possibility of a race condition here, but you are indeed correct that that could happen.

Long-term I think we should actually remove the list of target topics, if at all possible, as mentioned in #651, but in the meantime I think a simple lock here would be fine.

Comment (Nevon) [reply src/cluster/index.js]: Fixed in `091f5c`.

Comment (JaapRood) [reply src/cluster/index.js]: You reckon it's worth adding a test case that confirm the lock works as expected? It could be useful, but triggering race conditions reliably is hard and an ingredient for flaky tests.

Comment (Nevon) [reply src/cluster/index.js]: That was exactly my thinking. I would like to test it, but it also sounds nightmareish to get such a test to work consistently.

**Comment by ankon** [comment]
Mostly FYI: It seems I'm able to hit a lock timeout for this new lock in our production environment. What is worrying here is the number of "waiting locks" in the log messages goes continuously up, starting from 2 to 1789 after several hours when I finally killed the process.
