### PR TITLE
Fix typings for logger getters

### LINKED ISSUE #613: Consumer/Producer .logger() methods have incorrect return-value type annotations
It looks like the type annotations for Producer/Consumer `.logger()` methods are incorrect:

https://github.com/tulios/kafkajs/blob/fe7c0030620ffdc33e4141b9dd9dbff97d500f20/types/index.d.ts#L649

https://github.com/tulios/kafkajs/blob/fe7c0030620ffdc33e4141b9dd9dbff97d500f20/types/index.d.ts#L473

Both are listed as returning `Logger`, but that type is defined as a log-event function, not a logger object instance with `.info()` and other leveled logging functions. That means that using the logger in a consumer/producer requires something like the following, according to the current types (note the double-call `()()`): 

```ts
consumer.logger()({
  namespace: 'consumer-namespace',
  level: 'info',
  label: 'log-label',
  log: {
    timestamp: new Date(),
    message: 'log message goes here',
    extraData: 'other value'
  }
});
```

This doesn't match the documentation, which appears to imply that we should have leveled log functions on a logger instance (https://kafka.js.org/docs/custom-logger), like:

```ts
consumer.logger().info('log message goes here', {extraData: 'other value'});
```

### PR DESCRIPTION
**Pull request by Nevon**
This changes the type of `Logger`, which is technically breaking, but then again it was never correct in the first place, so maybe that's fine...?

FYI @gimbalgambit 

Fixes #613

### CODE REVIEW

File: types/tests.ts [hunk 1]
```diff
@@ -135,6 +139,7 @@ runProducer().catch(console.error)
 
 // ADMIN
 const admin = kafka.admin({ retry: { retries: 10 } })
+admin.logger().warn('Instantiatd admin')
```
Comment (Delapouite) [inline types/tests.ts]: typo: missing 'e'

Comment (Nevon) [reply types/tests.ts]: Fixed

**Comment by gimbalgambit** [comment]
Thanks, @Nevon! I think since the intent here is to fix a broken type assertion to be inline with the current spec, it's not a breaking change in a semver-bump sense... for whatever my opinion is worth. Appreciate the quick fix! 🙇‍♂️
