### PR TITLE
Skip incomplete record batches

### LINKED ISSUE #152: Devhelp - LZ4 decoding errors on master
On current master, after the [recent set of changes](https://github.com/tulios/kafkajs/compare/v1.3.1...master), decoding LZ4 messages with the [`kafkajs-lz4`](https://github.com/indix/kafkajs-lz4) package seem to break, with this stack trace —

```
{"level":"DEBUG","timestamp":"2018-10-08T09:30:11.878Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka1.com:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:12.425Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 2)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":44}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:12.668Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 2)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","error":"The version of API is not supported","correlationId":0,"payload":{"type":"Buffer","data":["filtered"]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:12.669Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 1)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":44}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:12.910Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 1)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":272,"data":{"errorCode":0,"apiVersions":[{"apiKey":0,"minVersion":0,"maxVersion":5},{"apiKey":1,"minVersion":0,"maxVersion":7},{"apiKey":2,"minVersion":0,"maxVersion":2},{"apiKey":3,"minVersion":0,"maxVersion":5},{"apiKey":4,"minVersion":0,"maxVersion":1},{"apiKey":5,"minVersion":0,"maxVersion":0},{"apiKey":6,"minVersion":0,"maxVersion":4},{"apiKey":7,"minVersion":0,"maxVersion":1},{"apiKey":8,"minVersion":0,"maxVersion":3},{"apiKey":9,"minVersion":0,"maxVersion":3},{"apiKey":10,"minVersion":0,"maxVersion":1},{"apiKey":11,"minVersion":0,"maxVersion":2},{"apiKey":12,"minVersion":0,"maxVersion":1},{"apiKey":13,"minVersion":0,"maxVersion":1},{"apiKey":14,"minVersion":0,"maxVersion":1},{"apiKey":15,"minVersion":0,"maxVersion":1},{"apiKey":16,"minVersion":0,"maxVersion":1},{"apiKey":17,"minVersion":0,"maxVersion":1},{"apiKey":18,"minVersion":0,"maxVersion":1},{"apiKey":19,"minVersion":0,"maxVersion":2},{"apiKey":20,"minVersion":0,"maxVersion":1},{"apiKey":21,"minVersion":0,"maxVersion":0},{"apiKey":22,"minVersion":0,"maxVersion":0},{"apiKey":23,"minVersion":0,"maxVersion":0},{"apiKey":24,"minVersion":0,"maxVersion":0},{"apiKey":25,"minVersion":0,"maxVersion":0},{"apiKey":26,"minVersion":0,"maxVersion":0},{"apiKey":27,"minVersion":0,"maxVersion":0},{"apiKey":28,"minVersion":0,"maxVersion":0},{"apiKey":29,"minVersion":0,"maxVersion":0},{"apiKey":30,"minVersion":0,"maxVersion":0},{"apiKey":31,"minVersion":0,"maxVersion":0},{"apiKey":32,"minVersion":0,"maxVersion":1},{"apiKey":33,"minVersion":0,"maxVersion":0},{"apiKey":34,"minVersion":0,"maxVersion":0},{"apiKey":35,"minVersion":0,"maxVersion":0},{"apiKey":36,"minVersion":0,"maxVersion":0},{"apiKey":37,"minVersion":0,"maxVersion":0},{"apiKey":38,"minVersion":0,"maxVersion":0},{"apiKey":39,"minVersion":0,"maxVersion":0},{"apiKey":40,"minVersion":0,"maxVersion":0},{"apiKey":41,"minVersion":0,"maxVersion":0},{"apiKey":42,"minVersion":0,"maxVersion":0}],"throttleTime":0}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:12.911Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka1.com:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:13.153Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 2)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":44}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:13.395Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 2)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","error":"The version of API is not supported","correlationId":0,"payload":{"type":"Buffer","data":["filtered"]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:13.395Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 1)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":44}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:13.635Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 1)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":272,"data":{"errorCode":0,"apiVersions":[{"apiKey":0,"minVersion":0,"maxVersion":5},{"apiKey":1,"minVersion":0,"maxVersion":7},{"apiKey":2,"minVersion":0,"maxVersion":2},{"apiKey":3,"minVersion":0,"maxVersion":5},{"apiKey":4,"minVersion":0,"maxVersion":1},{"apiKey":5,"minVersion":0,"maxVersion":0},{"apiKey":6,"minVersion":0,"maxVersion":4},{"apiKey":7,"minVersion":0,"maxVersion":1},{"apiKey":8,"minVersion":0,"maxVersion":3},{"apiKey":9,"minVersion":0,"maxVersion":3},{"apiKey":10,"minVersion":0,"maxVersion":1},{"apiKey":11,"minVersion":0,"maxVersion":2},{"apiKey":12,"minVersion":0,"maxVersion":1},{"apiKey":13,"minVersion":0,"maxVersion":1},{"apiKey":14,"minVersion":0,"maxVersion":1},{"apiKey":15,"minVersion":0,"maxVersion":1},{"apiKey":16,"minVersion":0,"maxVersion":1},{"apiKey":17,"minVersion":0,"maxVersion":1},{"apiKey":18,"minVersion":0,"maxVersion":1},{"apiKey":19,"minVersion":0,"maxVersion":2},{"apiKey":20,"minVersion":0,"maxVersion":1},{"apiKey":21,"minVersion":0,"maxVersion":0},{"apiKey":22,"minVersion":0,"maxVersion":0},{"apiKey":23,"minVersion":0,"maxVersion":0},{"apiKey":24,"minVersion":0,"maxVersion":0},{"apiKey":25,"minVersion":0,"maxVersion":0},{"apiKey":26,"minVersion":0,"maxVersion":0},{"apiKey":27,"minVersion":0,"maxVersion":0},{"apiKey":28,"minVersion":0,"maxVersion":0},{"apiKey":29,"minVersion":0,"maxVersion":0},{"apiKey":30,"minVersion":0,"maxVersion":0},{"apiKey":31,"minVersion":0,"maxVersion":0},{"apiKey":32,"minVersion":0,"maxVersion":1},{"apiKey":33,"minVersion":0,"maxVersion":0},{"apiKey":34,"minVersion":0,"maxVersion":0},{"apiKey":35,"minVersion":0,"maxVersion":0},{"apiKey":36,"minVersion":0,"maxVersion":0},{"apiKey":37,"minVersion":0,"maxVersion":0},{"apiKey":38,"minVersion":0,"maxVersion":0},{"apiKey":39,"minVersion":0,"maxVersion":0},{"apiKey":40,"minVersion":0,"maxVersion":0},{"apiKey":41,"minVersion":0,"maxVersion":0},{"apiKey":42,"minVersion":0,"maxVersion":0}],"throttleTime":0}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:13.641Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 4)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":2,"size":66}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.140Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 4)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":2,"size":13681,"data":{"throttleTime":0,"brokers":[{"nodeId":2,"host":"kafka2.com","port":9092,"rack":null},{"nodeId":5,"host":"kafka5","port":9092,"rack":null},{"nodeId":4,"host":"kafka4.com","port":9092,"rack":null},{"nodeId":1,"host":"kafka1.com","port":9092,"rack":null},{"nodeId":3,"host":"kafka3","port":9092,"rack":null}],"clusterId":"7QRYYnVdScOZOZEEj9pdpw","controllerId":3,"topicMetadata":[{"topicErrorCode":0,"topic":"topic1","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":137,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":146,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":218,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":227,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":92,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":101,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":200,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":173,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":209,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":182,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":191,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":254,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":83,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":155,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":164,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":245,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":110,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":119,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":128,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":236,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":23,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":95,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":104,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":391,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":131,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":122,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":194,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":176,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":77,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":86,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":185,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":158,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":167,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":50,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":364,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":59,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":373,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":32,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":68,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":41,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":382,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":140,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":113,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":149,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":346,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":355,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":394,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":53,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":367,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":62,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":134,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":35,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":376,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":8,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":349,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":44,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":17,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":358,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":26,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":125,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":331,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":304,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":340,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":80,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":89,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":286,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":295,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":116,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":71,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":98,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":107,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":313,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":322,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":385,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":11,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":307,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":74,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":388,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":56,"leader":2,"replicas":[2,1],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":397,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":262,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":298,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":370,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":29,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":343,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":38,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":379,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":352,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":47,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":244,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":226,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":253,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":325,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":361,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":334,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":20,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":2,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":235,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":316,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":289,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":65,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":271,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":280,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":319,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":5,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":184,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":193,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":265,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":301,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":175,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":256,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":337,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":211,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":283,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":292,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":166,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":274,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":247,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":14,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":328,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":220,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":229,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":202,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":238,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":310,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":277,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":142,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":151,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":223,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":250,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":259,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":232,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":124,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":106,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":133,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":205,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":214,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":160,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":169,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":178,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":115,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":187,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":196,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":241,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":268,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":369,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":181,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":163,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":172,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":46,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":387,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":118,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":127,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":199,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":136,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":208,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":217,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":100,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":82,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":109,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":91,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":190,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":396,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":55,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":64,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":378,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":73,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":145,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":154,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":360,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":85,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":399,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":58,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":67,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":94,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":139,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":300,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":381,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":40,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":354,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":390,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":49,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":130,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":336,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":345,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":4,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":13,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":372,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":148,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":121,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":157,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":22,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":363,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":31,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":76,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":103,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":112,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":309,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":318,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":327,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":16,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":357,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":97,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":312,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":7,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":348,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":393,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":79,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":88,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":294,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":303,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":375,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":70,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":384,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":43,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":52,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":276,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":249,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":285,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":258,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":330,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":267,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":25,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":339,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":366,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":34,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":240,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":321,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":61,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":10,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":189,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":225,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":306,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":37,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":180,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":333,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":342,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":1,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":207,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":216,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":288,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":324,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":297,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":198,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":270,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":279,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":252,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":351,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":19,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":28,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":261,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":234,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":243,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":315,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":282,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":174,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":147,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":183,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":156,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":255,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":228,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":264,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":129,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":138,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":210,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":219,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":291,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":120,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":165,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":237,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":246,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":192,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":201,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":273,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":60,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":186,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":213,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":222,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":87,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":96,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":168,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":177,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":383,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":392,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":150,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":159,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":132,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":141,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":105,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":114,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":123,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":195,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":204,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":69,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":78,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":231,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":332,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":90,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":63,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":99,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":45,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":386,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":395,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":54,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":341,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":171,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":377,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":72,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":144,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":81,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":153,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":126,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":162,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":359,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":27,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":368,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":36,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":108,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":135,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":117,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":350,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":323,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":9,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":18,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":389,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":48,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":362,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":21,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":57,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":263,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":272,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":344,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":317,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":3,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":353,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":12,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":84,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":93,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":102,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":326,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":299,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":335,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":308,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":380,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":75,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":281,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":290,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":30,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":371,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":39,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":111,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":398,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":66,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":15,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":356,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":230,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":42,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":51,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":257,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":24,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":338,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":33,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":347,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":374,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":6,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":221,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":248,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":320,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":329,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":302,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":203,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":275,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":212,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":311,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":284,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":293,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":365,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":266,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":239,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":314,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":179,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":152,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":188,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":260,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":269,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":143,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":170,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":215,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":287,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":161,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":242,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":251,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":197,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":224,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":296,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":206,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":233,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":305,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":278,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":0,"leader":1,"replicas":[1,2],"isr":[1,2]}]}]}}
{"level":"INFO","timestamp":"2018-10-08T09:30:14.143Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"kafka-reader-local"}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.144Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka2.com:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.649Z","logger":"kafkajs","message":"[Connection] Request GroupCoordinator(key: 10, version: 0)","broker":"kafka2.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":76}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.890Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 0)","broker":"kafka2.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":45,"data":{"errorCode":0,"coordinator":{"nodeId":4,"host":"kafka4.com","port":9092}}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.890Z","logger":"kafkajs","message":"[Cluster] Found group coordinator","nodeId":4}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:14.890Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka4.com:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:15.383Z","logger":"kafkajs","message":"[Connection] Request JoinGroup(key: 11, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":147}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:15.658Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":0,"size":272,"data":{"errorCode":0,"generationId":1,"groupProtocol":"RoundRobinAssigner","leaderId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","members":[{"memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","memberMetadata":{"type":"Buffer","data":["filtered"]}}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:15.659Z","logger":"kafkajs","message":"[ConsumerGroup] Chosen as group leader","groupId":"kafka-reader-local","generationId":1,"memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","topics":["topic1"]}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:15.659Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 4)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":3,"size":66}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.157Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 4)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":3,"size":13681,"data":{"throttleTime":0,"brokers":[{"nodeId":2,"host":"kafka2.com","port":9092,"rack":null},{"nodeId":5,"host":"kafka5","port":9092,"rack":null},{"nodeId":4,"host":"kafka4.com","port":9092,"rack":null},{"nodeId":1,"host":"kafka1.com","port":9092,"rack":null},{"nodeId":3,"host":"kafka3","port":9092,"rack":null}],"clusterId":"7QRYYnVdScOZOZEEj9pdpw","controllerId":3,"topicMetadata":[{"topicErrorCode":0,"topic":"topic1","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":137,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":146,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":218,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":227,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":92,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":101,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":200,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":173,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":209,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":182,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":191,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":254,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":83,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":155,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":164,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":245,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":110,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":119,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":128,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":236,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":23,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":95,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":104,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":391,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":131,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":122,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":194,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":176,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":77,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":86,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":185,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":158,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":167,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":50,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":364,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":59,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":373,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":32,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":68,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":41,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":382,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":140,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":113,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":149,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":346,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":355,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":394,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":53,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":367,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":62,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":134,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":35,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":376,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":8,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":349,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":44,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":17,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":358,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":26,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":125,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":331,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":304,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":340,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":80,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":89,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":286,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":295,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":116,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":71,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":98,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":107,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":313,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":322,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":385,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":11,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":307,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":74,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":388,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":56,"leader":2,"replicas":[2,1],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":397,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":262,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":298,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":370,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":29,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":343,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":38,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":379,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":352,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":47,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":244,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":226,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":253,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":325,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":361,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":334,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":20,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":2,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":235,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":316,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":289,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":65,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":271,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":280,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":319,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":5,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":184,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":193,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":265,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":301,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":175,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":256,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":337,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":211,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":283,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":292,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":166,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":274,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":247,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":14,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":328,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":220,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":229,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":202,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":238,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":310,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":277,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":142,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":151,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":223,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":250,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":259,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":232,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":124,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":106,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":133,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":205,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":214,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":160,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":169,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":178,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":115,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":187,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":196,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":241,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":268,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":369,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":181,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":163,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":172,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":46,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":387,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":118,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":127,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":199,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":136,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":208,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":217,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":100,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":82,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":109,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":91,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":190,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":396,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":55,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":64,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":378,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":73,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":145,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":154,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":360,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":85,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":399,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":58,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":67,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":94,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":139,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":300,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":381,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":40,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":354,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":390,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":49,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":130,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":336,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":345,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":4,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":13,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":372,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":148,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":121,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":157,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":22,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":363,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":31,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":76,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":103,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":112,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":309,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":318,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":327,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":16,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":357,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":97,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":312,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":7,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":348,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":393,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":79,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":88,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":294,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":303,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":375,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":70,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":384,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":43,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":52,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":276,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":249,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":285,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":258,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":330,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":267,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":25,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":339,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":366,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":34,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":240,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":321,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":61,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":10,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":189,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":225,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":306,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":37,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":180,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":333,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":342,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":1,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":207,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":216,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":288,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":324,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":297,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":198,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":270,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":279,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":252,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":351,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":19,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":28,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":261,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":234,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":243,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":315,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":282,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":174,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":147,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":183,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":156,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":255,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":228,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":264,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":129,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":138,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":210,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":219,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":291,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":120,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":165,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":237,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":246,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":192,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":201,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":273,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":60,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":186,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":213,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":222,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":87,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":96,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":168,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":177,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":383,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":392,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":150,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":159,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":132,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":141,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":105,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":114,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":123,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":195,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":204,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":69,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":78,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":231,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":332,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":90,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":63,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":99,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":45,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":386,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":395,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":54,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":341,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":171,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":377,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":72,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":144,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":81,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":153,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":126,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":162,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":359,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":27,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":368,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":36,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":108,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":135,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":117,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":350,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":323,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":9,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":18,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":389,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":48,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":362,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":21,"leader":2,"replicas":[2,3],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":57,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":263,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":272,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":344,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":317,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":3,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":353,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":12,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":84,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":93,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":102,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":326,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":299,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":335,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":308,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":380,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":75,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":281,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":290,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":30,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":371,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":39,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":111,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":398,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":66,"leader":2,"replicas":[2,4],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":15,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":356,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":230,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":42,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":51,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":257,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":24,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":338,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":33,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":347,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":374,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":6,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":221,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":248,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":320,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":329,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":302,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":203,"leader":4,"replicas":[4,5],"isr":[4,5]},{"partitionErrorCode":0,"partitionId":275,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":212,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":311,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":284,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":293,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":365,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":266,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":239,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":314,"leader":5,"replicas":[5,3],"isr":[5,3]},{"partitionErrorCode":0,"partitionId":179,"leader":5,"replicas":[5,4],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":152,"leader":3,"replicas":[3,1],"isr":[3,1]},{"partitionErrorCode":0,"partitionId":188,"leader":4,"replicas":[4,1],"isr":[4,1]},{"partitionErrorCode":0,"partitionId":260,"leader":1,"replicas":[1,2],"isr":[1,2]},{"partitionErrorCode":0,"partitionId":269,"leader":5,"replicas":[5,2],"isr":[5,2]},{"partitionErrorCode":0,"partitionId":143,"leader":4,"replicas":[4,5],"isr":[5,4]},{"partitionErrorCode":0,"partitionId":170,"leader":1,"replicas":[1,4],"isr":[1,4]},{"partitionErrorCode":0,"partitionId":215,"leader":1,"replicas":[1,5],"isr":[1,5]},{"partitionErrorCode":0,"partitionId":287,"leader":3,"replicas":[3,5],"isr":[3]},{"partitionErrorCode":0,"partitionId":161,"leader":2,"replicas":[2,3],"isr":[2,3]},{"partitionErrorCode":0,"partitionId":242,"leader":3,"replicas":[3,4],"isr":[3,4]},{"partitionErrorCode":0,"partitionId":251,"leader":2,"replicas":[2,5],"isr":[2,5]},{"partitionErrorCode":0,"partitionId":197,"leader":3,"replicas":[3,2],"isr":[3,2]},{"partitionErrorCode":0,"partitionId":224,"leader":5,"replicas":[5,1],"isr":[5,1]},{"partitionErrorCode":0,"partitionId":296,"leader":2,"replicas":[2,1],"isr":[2,1]},{"partitionErrorCode":0,"partitionId":206,"leader":2,"replicas":[2,4],"isr":[2,4]},{"partitionErrorCode":0,"partitionId":233,"leader":4,"replicas":[4,2],"isr":[4,2]},{"partitionErrorCode":0,"partitionId":305,"leader":1,"replicas":[1,3],"isr":[1]},{"partitionErrorCode":0,"partitionId":278,"leader":4,"replicas":[4,3],"isr":[4,3]},{"partitionErrorCode":0,"partitionId":0,"leader":1,"replicas":[1,2],"isr":[1,2]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.162Z","logger":"kafkajs","message":"[ConsumerGroup] Group assignment","groupId":"kafka-reader-local","generationId":1,"topics":["topic1"],"groupProtocol":"RoundRobinAssigner","assignment":[{"memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","memberAssignment":{"type":"Buffer","data":["filtered"]}}]}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.166Z","logger":"kafkajs","message":"[Connection] Request SyncGroup(key: 14, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":1857}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.435Z","logger":"kafkajs","message":"[Connection] Response SyncGroup(key: 14, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":1641,"data":{"errorCode":0,"memberAssignment":{"type":"Buffer","data":["filtered"]}}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.436Z","logger":"kafkajs","message":"[ConsumerGroup] Received assignment","groupId":"kafka-reader-local","generationId":1,"memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","memberAssignment":{"topic1":[137,146,218,227,92,101,200,173,209,182,191,254,83,155,164,245,110,119,128,236,23,95,104,391,131,122,194,176,77,86,185,158,167,50,364,59,373,32,68,41,382,140,113,149,346,355,394,53,367,62,134,35,376,8,349,44,17,358,26,125,331,304,340,80,89,286,295,116,71,98,107,313,322,385,11,307,74,388,56,397,262,298,370,29,343,38,379,352,47,244,226,253,325,361,334,20,2,235,316,289,65,271,280,319,5,184,193,265,301,175,256,337,211,283,292,166,274,247,14,328,220,229,202,238,310,277,142,151,223,250,259,232,124,106,133,205,214,160,169,178,115,187,196,241,268,369,181,163,172,46,387,118,127,199,136,208,217,100,82,109,91,190,396,55,64,378,73,145,154,360,85,399,58,67,94,139,300,381,40,354,390,49,130,336,345,4,13,372,148,121,157,22,363,31,76,103,112,309,318,327,16,357,97,312,7,348,393,79,88,294,303,375,70,384,43,52,276,249,285,258,330,267,25,339,366,34,240,321,61,10,189,225,306,37,180,333,342,1,207,216,288,324,297,198,270,279,252,351,19,28,261,234,243,315,282,174,147,183,156,255,228,264,129,138,210,219,291,120,165,237,246,192,201,273,60,186,213,222,87,96,168,177,383,392,150,159,132,141,105,114,123,195,204,69,78,231,332,90,63,99,45,386,395,54,341,171,377,72,144,81,153,126,162,359,27,368,36,108,135,117,350,323,9,18,389,48,362,21,57,263,272,344,317,3,353,12,84,93,102,326,299,335,308,380,75,281,290,30,371,39,111,398,66,15,356,230,42,51,257,24,338,33,347,374,6,221,248,320,329,302,203,275,212,311,284,293,365,266,239,314,179,152,188,260,269,143,170,215,287,161,242,251,197,224,296,206,233,305,278,0]}}
{"level":"INFO","timestamp":"2018-10-08T09:30:16.437Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"kafka-reader-local","memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","leaderId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","isLeader":true,"memberAssignment":{"topic1":[137,146,218,227,92,101,200,173,209,182,191,254,83,155,164,245,110,119,128,236,23,95,104,391,131,122,194,176,77,86,185,158,167,50,364,59,373,32,68,41,382,140,113,149,346,355,394,53,367,62,134,35,376,8,349,44,17,358,26,125,331,304,340,80,89,286,295,116,71,98,107,313,322,385,11,307,74,388,56,397,262,298,370,29,343,38,379,352,47,244,226,253,325,361,334,20,2,235,316,289,65,271,280,319,5,184,193,265,301,175,256,337,211,283,292,166,274,247,14,328,220,229,202,238,310,277,142,151,223,250,259,232,124,106,133,205,214,160,169,178,115,187,196,241,268,369,181,163,172,46,387,118,127,199,136,208,217,100,82,109,91,190,396,55,64,378,73,145,154,360,85,399,58,67,94,139,300,381,40,354,390,49,130,336,345,4,13,372,148,121,157,22,363,31,76,103,112,309,318,327,16,357,97,312,7,348,393,79,88,294,303,375,70,384,43,52,276,249,285,258,330,267,25,339,366,34,240,321,61,10,189,225,306,37,180,333,342,1,207,216,288,324,297,198,270,279,252,351,19,28,261,234,243,315,282,174,147,183,156,255,228,264,129,138,210,219,291,120,165,237,246,192,201,273,60,186,213,222,87,96,168,177,383,392,150,159,132,141,105,114,123,195,204,69,78,231,332,90,63,99,45,386,395,54,341,171,377,72,144,81,153,126,162,359,27,368,36,108,135,117,350,323,9,18,389,48,362,21,57,263,272,344,317,3,353,12,84,93,102,326,299,335,308,380,75,281,290,30,371,39,111,398,66,15,356,230,42,51,257,24,338,33,347,374,6,221,248,320,329,302,203,275,212,311,284,293,365,266,239,314,179,152,188,260,269,143,170,215,287,161,242,251,197,224,296,206,233,305,278,0]},"duration":2294}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.444Z","logger":"kafkajs","message":"[Connection] Request OffsetFetch(key: 9, version: 2)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":2,"size":1701}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.698Z","logger":"kafkajs","message":"[Connection] Response OffsetFetch(key: 9, version: 2)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":2,"size":6431,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":0,"offset":"-1","metadata":"","errorCode":0},{"partition":1,"offset":"-1","metadata":"","errorCode":0},{"partition":2,"offset":"-1","metadata":"","errorCode":0},{"partition":3,"offset":"-1","metadata":"","errorCode":0},{"partition":4,"offset":"-1","metadata":"","errorCode":0},{"partition":5,"offset":"-1","metadata":"","errorCode":0},{"partition":6,"offset":"-1","metadata":"","errorCode":0},{"partition":7,"offset":"-1","metadata":"","errorCode":0},{"partition":8,"offset":"-1","metadata":"","errorCode":0},{"partition":9,"offset":"-1","metadata":"","errorCode":0},{"partition":10,"offset":"-1","metadata":"","errorCode":0},{"partition":11,"offset":"-1","metadata":"","errorCode":0},{"partition":12,"offset":"-1","metadata":"","errorCode":0},{"partition":13,"offset":"-1","metadata":"","errorCode":0},{"partition":14,"offset":"-1","metadata":"","errorCode":0},{"partition":15,"offset":"-1","metadata":"","errorCode":0},{"partition":16,"offset":"-1","metadata":"","errorCode":0},{"partition":17,"offset":"-1","metadata":"","errorCode":0},{"partition":18,"offset":"-1","metadata":"","errorCode":0},{"partition":19,"offset":"-1","metadata":"","errorCode":0},{"partition":20,"offset":"-1","metadata":"","errorCode":0},{"partition":21,"offset":"-1","metadata":"","errorCode":0},{"partition":22,"offset":"-1","metadata":"","errorCode":0},{"partition":23,"offset":"-1","metadata":"","errorCode":0},{"partition":24,"offset":"-1","metadata":"","errorCode":0},{"partition":25,"offset":"-1","metadata":"","errorCode":0},{"partition":26,"offset":"-1","metadata":"","errorCode":0},{"partition":27,"offset":"-1","metadata":"","errorCode":0},{"partition":28,"offset":"-1","metadata":"","errorCode":0},{"partition":29,"offset":"-1","metadata":"","errorCode":0},{"partition":30,"offset":"-1","metadata":"","errorCode":0},{"partition":31,"offset":"-1","metadata":"","errorCode":0},{"partition":32,"offset":"-1","metadata":"","errorCode":0},{"partition":33,"offset":"-1","metadata":"","errorCode":0},{"partition":34,"offset":"-1","metadata":"","errorCode":0},{"partition":35,"offset":"-1","metadata":"","errorCode":0},{"partition":36,"offset":"-1","metadata":"","errorCode":0},{"partition":37,"offset":"-1","metadata":"","errorCode":0},{"partition":38,"offset":"-1","metadata":"","errorCode":0},{"partition":39,"offset":"-1","metadata":"","errorCode":0},{"partition":40,"offset":"-1","metadata":"","errorCode":0},{"partition":41,"offset":"-1","metadata":"","errorCode":0},{"partition":42,"offset":"-1","metadata":"","errorCode":0},{"partition":43,"offset":"-1","metadata":"","errorCode":0},{"partition":44,"offset":"-1","metadata":"","errorCode":0},{"partition":45,"offset":"-1","metadata":"","errorCode":0},{"partition":46,"offset":"-1","metadata":"","errorCode":0},{"partition":47,"offset":"-1","metadata":"","errorCode":0},{"partition":48,"offset":"-1","metadata":"","errorCode":0},{"partition":49,"offset":"-1","metadata":"","errorCode":0},{"partition":50,"offset":"-1","metadata":"","errorCode":0},{"partition":51,"offset":"-1","metadata":"","errorCode":0},{"partition":52,"offset":"-1","metadata":"","errorCode":0},{"partition":53,"offset":"-1","metadata":"","errorCode":0},{"partition":54,"offset":"-1","metadata":"","errorCode":0},{"partition":55,"offset":"-1","metadata":"","errorCode":0},{"partition":56,"offset":"-1","metadata":"","errorCode":0},{"partition":57,"offset":"-1","metadata":"","errorCode":0},{"partition":58,"offset":"-1","metadata":"","errorCode":0},{"partition":59,"offset":"-1","metadata":"","errorCode":0},{"partition":60,"offset":"-1","metadata":"","errorCode":0},{"partition":61,"offset":"-1","metadata":"","errorCode":0},{"partition":62,"offset":"-1","metadata":"","errorCode":0},{"partition":63,"offset":"-1","metadata":"","errorCode":0},{"partition":64,"offset":"-1","metadata":"","errorCode":0},{"partition":65,"offset":"-1","metadata":"","errorCode":0},{"partition":66,"offset":"-1","metadata":"","errorCode":0},{"partition":67,"offset":"-1","metadata":"","errorCode":0},{"partition":68,"offset":"-1","metadata":"","errorCode":0},{"partition":69,"offset":"-1","metadata":"","errorCode":0},{"partition":70,"offset":"-1","metadata":"","errorCode":0},{"partition":71,"offset":"-1","metadata":"","errorCode":0},{"partition":72,"offset":"-1","metadata":"","errorCode":0},{"partition":73,"offset":"-1","metadata":"","errorCode":0},{"partition":74,"offset":"-1","metadata":"","errorCode":0},{"partition":75,"offset":"-1","metadata":"","errorCode":0},{"partition":76,"offset":"-1","metadata":"","errorCode":0},{"partition":77,"offset":"-1","metadata":"","errorCode":0},{"partition":78,"offset":"-1","metadata":"","errorCode":0},{"partition":79,"offset":"-1","metadata":"","errorCode":0},{"partition":80,"offset":"-1","metadata":"","errorCode":0},{"partition":81,"offset":"-1","metadata":"","errorCode":0},{"partition":82,"offset":"-1","metadata":"","errorCode":0},{"partition":83,"offset":"-1","metadata":"","errorCode":0},{"partition":84,"offset":"-1","metadata":"","errorCode":0},{"partition":85,"offset":"-1","metadata":"","errorCode":0},{"partition":86,"offset":"-1","metadata":"","errorCode":0},{"partition":87,"offset":"-1","metadata":"","errorCode":0},{"partition":88,"offset":"-1","metadata":"","errorCode":0},{"partition":89,"offset":"-1","metadata":"","errorCode":0},{"partition":90,"offset":"-1","metadata":"","errorCode":0},{"partition":91,"offset":"-1","metadata":"","errorCode":0},{"partition":92,"offset":"-1","metadata":"","errorCode":0},{"partition":93,"offset":"-1","metadata":"","errorCode":0},{"partition":94,"offset":"-1","metadata":"","errorCode":0},{"partition":95,"offset":"-1","metadata":"","errorCode":0},{"partition":96,"offset":"-1","metadata":"","errorCode":0},{"partition":97,"offset":"-1","metadata":"","errorCode":0},{"partition":98,"offset":"-1","metadata":"","errorCode":0},{"partition":99,"offset":"-1","metadata":"","errorCode":0},{"partition":100,"offset":"-1","metadata":"","errorCode":0},{"partition":101,"offset":"-1","metadata":"","errorCode":0},{"partition":102,"offset":"-1","metadata":"","errorCode":0},{"partition":103,"offset":"-1","metadata":"","errorCode":0},{"partition":104,"offset":"-1","metadata":"","errorCode":0},{"partition":105,"offset":"-1","metadata":"","errorCode":0},{"partition":106,"offset":"-1","metadata":"","errorCode":0},{"partition":107,"offset":"-1","metadata":"","errorCode":0},{"partition":108,"offset":"-1","metadata":"","errorCode":0},{"partition":109,"offset":"-1","metadata":"","errorCode":0},{"partition":110,"offset":"-1","metadata":"","errorCode":0},{"partition":111,"offset":"-1","metadata":"","errorCode":0},{"partition":112,"offset":"-1","metadata":"","errorCode":0},{"partition":113,"offset":"-1","metadata":"","errorCode":0},{"partition":114,"offset":"-1","metadata":"","errorCode":0},{"partition":115,"offset":"-1","metadata":"","errorCode":0},{"partition":116,"offset":"-1","metadata":"","errorCode":0},{"partition":117,"offset":"-1","metadata":"","errorCode":0},{"partition":118,"offset":"-1","metadata":"","errorCode":0},{"partition":119,"offset":"-1","metadata":"","errorCode":0},{"partition":120,"offset":"-1","metadata":"","errorCode":0},{"partition":121,"offset":"-1","metadata":"","errorCode":0},{"partition":122,"offset":"-1","metadata":"","errorCode":0},{"partition":123,"offset":"-1","metadata":"","errorCode":0},{"partition":124,"offset":"-1","metadata":"","errorCode":0},{"partition":125,"offset":"-1","metadata":"","errorCode":0},{"partition":126,"offset":"-1","metadata":"","errorCode":0},{"partition":127,"offset":"-1","metadata":"","errorCode":0},{"partition":128,"offset":"-1","metadata":"","errorCode":0},{"partition":129,"offset":"-1","metadata":"","errorCode":0},{"partition":130,"offset":"-1","metadata":"","errorCode":0},{"partition":131,"offset":"-1","metadata":"","errorCode":0},{"partition":132,"offset":"-1","metadata":"","errorCode":0},{"partition":133,"offset":"-1","metadata":"","errorCode":0},{"partition":134,"offset":"-1","metadata":"","errorCode":0},{"partition":135,"offset":"-1","metadata":"","errorCode":0},{"partition":136,"offset":"-1","metadata":"","errorCode":0},{"partition":137,"offset":"-1","metadata":"","errorCode":0},{"partition":138,"offset":"-1","metadata":"","errorCode":0},{"partition":139,"offset":"-1","metadata":"","errorCode":0},{"partition":140,"offset":"-1","metadata":"","errorCode":0},{"partition":141,"offset":"-1","metadata":"","errorCode":0},{"partition":142,"offset":"-1","metadata":"","errorCode":0},{"partition":143,"offset":"-1","metadata":"","errorCode":0},{"partition":144,"offset":"-1","metadata":"","errorCode":0},{"partition":145,"offset":"-1","metadata":"","errorCode":0},{"partition":146,"offset":"-1","metadata":"","errorCode":0},{"partition":147,"offset":"-1","metadata":"","errorCode":0},{"partition":148,"offset":"-1","metadata":"","errorCode":0},{"partition":149,"offset":"-1","metadata":"","errorCode":0},{"partition":150,"offset":"-1","metadata":"","errorCode":0},{"partition":151,"offset":"-1","metadata":"","errorCode":0},{"partition":152,"offset":"-1","metadata":"","errorCode":0},{"partition":153,"offset":"-1","metadata":"","errorCode":0},{"partition":154,"offset":"-1","metadata":"","errorCode":0},{"partition":155,"offset":"-1","metadata":"","errorCode":0},{"partition":156,"offset":"-1","metadata":"","errorCode":0},{"partition":157,"offset":"-1","metadata":"","errorCode":0},{"partition":158,"offset":"-1","metadata":"","errorCode":0},{"partition":159,"offset":"-1","metadata":"","errorCode":0},{"partition":160,"offset":"-1","metadata":"","errorCode":0},{"partition":161,"offset":"-1","metadata":"","errorCode":0},{"partition":162,"offset":"-1","metadata":"","errorCode":0},{"partition":163,"offset":"-1","metadata":"","errorCode":0},{"partition":164,"offset":"-1","metadata":"","errorCode":0},{"partition":165,"offset":"-1","metadata":"","errorCode":0},{"partition":166,"offset":"-1","metadata":"","errorCode":0},{"partition":167,"offset":"-1","metadata":"","errorCode":0},{"partition":168,"offset":"-1","metadata":"","errorCode":0},{"partition":169,"offset":"-1","metadata":"","errorCode":0},{"partition":170,"offset":"-1","metadata":"","errorCode":0},{"partition":171,"offset":"-1","metadata":"","errorCode":0},{"partition":172,"offset":"-1","metadata":"","errorCode":0},{"partition":173,"offset":"-1","metadata":"","errorCode":0},{"partition":174,"offset":"-1","metadata":"","errorCode":0},{"partition":175,"offset":"-1","metadata":"","errorCode":0},{"partition":176,"offset":"-1","metadata":"","errorCode":0},{"partition":177,"offset":"-1","metadata":"","errorCode":0},{"partition":178,"offset":"-1","metadata":"","errorCode":0},{"partition":179,"offset":"-1","metadata":"","errorCode":0},{"partition":180,"offset":"-1","metadata":"","errorCode":0},{"partition":181,"offset":"-1","metadata":"","errorCode":0},{"partition":182,"offset":"-1","metadata":"","errorCode":0},{"partition":183,"offset":"-1","metadata":"","errorCode":0},{"partition":184,"offset":"-1","metadata":"","errorCode":0},{"partition":185,"offset":"-1","metadata":"","errorCode":0},{"partition":186,"offset":"-1","metadata":"","errorCode":0},{"partition":187,"offset":"-1","metadata":"","errorCode":0},{"partition":188,"offset":"-1","metadata":"","errorCode":0},{"partition":189,"offset":"-1","metadata":"","errorCode":0},{"partition":190,"offset":"-1","metadata":"","errorCode":0},{"partition":191,"offset":"-1","metadata":"","errorCode":0},{"partition":192,"offset":"-1","metadata":"","errorCode":0},{"partition":193,"offset":"-1","metadata":"","errorCode":0},{"partition":194,"offset":"-1","metadata":"","errorCode":0},{"partition":195,"offset":"-1","metadata":"","errorCode":0},{"partition":196,"offset":"-1","metadata":"","errorCode":0},{"partition":197,"offset":"-1","metadata":"","errorCode":0},{"partition":198,"offset":"-1","metadata":"","errorCode":0},{"partition":199,"offset":"-1","metadata":"","errorCode":0},{"partition":200,"offset":"-1","metadata":"","errorCode":0},{"partition":201,"offset":"-1","metadata":"","errorCode":0},{"partition":202,"offset":"-1","metadata":"","errorCode":0},{"partition":203,"offset":"-1","metadata":"","errorCode":0},{"partition":204,"offset":"-1","metadata":"","errorCode":0},{"partition":205,"offset":"-1","metadata":"","errorCode":0},{"partition":206,"offset":"-1","metadata":"","errorCode":0},{"partition":207,"offset":"-1","metadata":"","errorCode":0},{"partition":208,"offset":"-1","metadata":"","errorCode":0},{"partition":209,"offset":"-1","metadata":"","errorCode":0},{"partition":210,"offset":"-1","metadata":"","errorCode":0},{"partition":211,"offset":"-1","metadata":"","errorCode":0},{"partition":212,"offset":"-1","metadata":"","errorCode":0},{"partition":213,"offset":"-1","metadata":"","errorCode":0},{"partition":214,"offset":"-1","metadata":"","errorCode":0},{"partition":215,"offset":"-1","metadata":"","errorCode":0},{"partition":216,"offset":"-1","metadata":"","errorCode":0},{"partition":217,"offset":"-1","metadata":"","errorCode":0},{"partition":218,"offset":"-1","metadata":"","errorCode":0},{"partition":219,"offset":"-1","metadata":"","errorCode":0},{"partition":220,"offset":"-1","metadata":"","errorCode":0},{"partition":221,"offset":"-1","metadata":"","errorCode":0},{"partition":222,"offset":"-1","metadata":"","errorCode":0},{"partition":223,"offset":"-1","metadata":"","errorCode":0},{"partition":224,"offset":"-1","metadata":"","errorCode":0},{"partition":225,"offset":"-1","metadata":"","errorCode":0},{"partition":226,"offset":"-1","metadata":"","errorCode":0},{"partition":227,"offset":"-1","metadata":"","errorCode":0},{"partition":228,"offset":"-1","metadata":"","errorCode":0},{"partition":229,"offset":"-1","metadata":"","errorCode":0},{"partition":230,"offset":"-1","metadata":"","errorCode":0},{"partition":231,"offset":"-1","metadata":"","errorCode":0},{"partition":232,"offset":"-1","metadata":"","errorCode":0},{"partition":233,"offset":"-1","metadata":"","errorCode":0},{"partition":234,"offset":"-1","metadata":"","errorCode":0},{"partition":235,"offset":"-1","metadata":"","errorCode":0},{"partition":236,"offset":"-1","metadata":"","errorCode":0},{"partition":237,"offset":"-1","metadata":"","errorCode":0},{"partition":238,"offset":"-1","metadata":"","errorCode":0},{"partition":239,"offset":"-1","metadata":"","errorCode":0},{"partition":240,"offset":"-1","metadata":"","errorCode":0},{"partition":241,"offset":"-1","metadata":"","errorCode":0},{"partition":242,"offset":"-1","metadata":"","errorCode":0},{"partition":243,"offset":"-1","metadata":"","errorCode":0},{"partition":244,"offset":"-1","metadata":"","errorCode":0},{"partition":245,"offset":"-1","metadata":"","errorCode":0},{"partition":246,"offset":"-1","metadata":"","errorCode":0},{"partition":247,"offset":"-1","metadata":"","errorCode":0},{"partition":248,"offset":"-1","metadata":"","errorCode":0},{"partition":249,"offset":"-1","metadata":"","errorCode":0},{"partition":250,"offset":"-1","metadata":"","errorCode":0},{"partition":251,"offset":"-1","metadata":"","errorCode":0},{"partition":252,"offset":"-1","metadata":"","errorCode":0},{"partition":253,"offset":"-1","metadata":"","errorCode":0},{"partition":254,"offset":"-1","metadata":"","errorCode":0},{"partition":255,"offset":"-1","metadata":"","errorCode":0},{"partition":256,"offset":"-1","metadata":"","errorCode":0},{"partition":257,"offset":"-1","metadata":"","errorCode":0},{"partition":258,"offset":"-1","metadata":"","errorCode":0},{"partition":259,"offset":"-1","metadata":"","errorCode":0},{"partition":260,"offset":"-1","metadata":"","errorCode":0},{"partition":261,"offset":"-1","metadata":"","errorCode":0},{"partition":262,"offset":"-1","metadata":"","errorCode":0},{"partition":263,"offset":"-1","metadata":"","errorCode":0},{"partition":264,"offset":"-1","metadata":"","errorCode":0},{"partition":265,"offset":"-1","metadata":"","errorCode":0},{"partition":266,"offset":"-1","metadata":"","errorCode":0},{"partition":267,"offset":"-1","metadata":"","errorCode":0},{"partition":268,"offset":"-1","metadata":"","errorCode":0},{"partition":269,"offset":"-1","metadata":"","errorCode":0},{"partition":270,"offset":"-1","metadata":"","errorCode":0},{"partition":271,"offset":"-1","metadata":"","errorCode":0},{"partition":272,"offset":"-1","metadata":"","errorCode":0},{"partition":273,"offset":"-1","metadata":"","errorCode":0},{"partition":274,"offset":"-1","metadata":"","errorCode":0},{"partition":275,"offset":"-1","metadata":"","errorCode":0},{"partition":276,"offset":"-1","metadata":"","errorCode":0},{"partition":277,"offset":"-1","metadata":"","errorCode":0},{"partition":278,"offset":"-1","metadata":"","errorCode":0},{"partition":279,"offset":"-1","metadata":"","errorCode":0},{"partition":280,"offset":"-1","metadata":"","errorCode":0},{"partition":281,"offset":"-1","metadata":"","errorCode":0},{"partition":282,"offset":"-1","metadata":"","errorCode":0},{"partition":283,"offset":"-1","metadata":"","errorCode":0},{"partition":284,"offset":"-1","metadata":"","errorCode":0},{"partition":285,"offset":"-1","metadata":"","errorCode":0},{"partition":286,"offset":"-1","metadata":"","errorCode":0},{"partition":287,"offset":"-1","metadata":"","errorCode":0},{"partition":288,"offset":"-1","metadata":"","errorCode":0},{"partition":289,"offset":"-1","metadata":"","errorCode":0},{"partition":290,"offset":"-1","metadata":"","errorCode":0},{"partition":291,"offset":"-1","metadata":"","errorCode":0},{"partition":292,"offset":"-1","metadata":"","errorCode":0},{"partition":293,"offset":"-1","metadata":"","errorCode":0},{"partition":294,"offset":"-1","metadata":"","errorCode":0},{"partition":295,"offset":"-1","metadata":"","errorCode":0},{"partition":296,"offset":"-1","metadata":"","errorCode":0},{"partition":297,"offset":"-1","metadata":"","errorCode":0},{"partition":298,"offset":"-1","metadata":"","errorCode":0},{"partition":299,"offset":"-1","metadata":"","errorCode":0},{"partition":300,"offset":"-1","metadata":"","errorCode":0},{"partition":301,"offset":"-1","metadata":"","errorCode":0},{"partition":302,"offset":"-1","metadata":"","errorCode":0},{"partition":303,"offset":"-1","metadata":"","errorCode":0},{"partition":304,"offset":"-1","metadata":"","errorCode":0},{"partition":305,"offset":"-1","metadata":"","errorCode":0},{"partition":306,"offset":"-1","metadata":"","errorCode":0},{"partition":307,"offset":"-1","metadata":"","errorCode":0},{"partition":308,"offset":"-1","metadata":"","errorCode":0},{"partition":309,"offset":"-1","metadata":"","errorCode":0},{"partition":310,"offset":"-1","metadata":"","errorCode":0},{"partition":311,"offset":"-1","metadata":"","errorCode":0},{"partition":312,"offset":"-1","metadata":"","errorCode":0},{"partition":313,"offset":"-1","metadata":"","errorCode":0},{"partition":314,"offset":"-1","metadata":"","errorCode":0},{"partition":315,"offset":"-1","metadata":"","errorCode":0},{"partition":316,"offset":"-1","metadata":"","errorCode":0},{"partition":317,"offset":"-1","metadata":"","errorCode":0},{"partition":318,"offset":"-1","metadata":"","errorCode":0},{"partition":319,"offset":"-1","metadata":"","errorCode":0},{"partition":320,"offset":"-1","metadata":"","errorCode":0},{"partition":321,"offset":"-1","metadata":"","errorCode":0},{"partition":322,"offset":"-1","metadata":"","errorCode":0},{"partition":323,"offset":"-1","metadata":"","errorCode":0},{"partition":324,"offset":"-1","metadata":"","errorCode":0},{"partition":325,"offset":"-1","metadata":"","errorCode":0},{"partition":326,"offset":"-1","metadata":"","errorCode":0},{"partition":327,"offset":"-1","metadata":"","errorCode":0},{"partition":328,"offset":"-1","metadata":"","errorCode":0},{"partition":329,"offset":"-1","metadata":"","errorCode":0},{"partition":330,"offset":"-1","metadata":"","errorCode":0},{"partition":331,"offset":"-1","metadata":"","errorCode":0},{"partition":332,"offset":"-1","metadata":"","errorCode":0},{"partition":333,"offset":"-1","metadata":"","errorCode":0},{"partition":334,"offset":"-1","metadata":"","errorCode":0},{"partition":335,"offset":"-1","metadata":"","errorCode":0},{"partition":336,"offset":"-1","metadata":"","errorCode":0},{"partition":337,"offset":"-1","metadata":"","errorCode":0},{"partition":338,"offset":"-1","metadata":"","errorCode":0},{"partition":339,"offset":"-1","metadata":"","errorCode":0},{"partition":340,"offset":"-1","metadata":"","errorCode":0},{"partition":341,"offset":"-1","metadata":"","errorCode":0},{"partition":342,"offset":"-1","metadata":"","errorCode":0},{"partition":343,"offset":"-1","metadata":"","errorCode":0},{"partition":344,"offset":"-1","metadata":"","errorCode":0},{"partition":345,"offset":"-1","metadata":"","errorCode":0},{"partition":346,"offset":"-1","metadata":"","errorCode":0},{"partition":347,"offset":"-1","metadata":"","errorCode":0},{"partition":348,"offset":"-1","metadata":"","errorCode":0},{"partition":349,"offset":"-1","metadata":"","errorCode":0},{"partition":350,"offset":"-1","metadata":"","errorCode":0},{"partition":351,"offset":"-1","metadata":"","errorCode":0},{"partition":352,"offset":"-1","metadata":"","errorCode":0},{"partition":353,"offset":"-1","metadata":"","errorCode":0},{"partition":354,"offset":"-1","metadata":"","errorCode":0},{"partition":355,"offset":"-1","metadata":"","errorCode":0},{"partition":356,"offset":"-1","metadata":"","errorCode":0},{"partition":357,"offset":"-1","metadata":"","errorCode":0},{"partition":358,"offset":"-1","metadata":"","errorCode":0},{"partition":359,"offset":"-1","metadata":"","errorCode":0},{"partition":360,"offset":"-1","metadata":"","errorCode":0},{"partition":361,"offset":"-1","metadata":"","errorCode":0},{"partition":362,"offset":"-1","metadata":"","errorCode":0},{"partition":363,"offset":"-1","metadata":"","errorCode":0},{"partition":364,"offset":"-1","metadata":"","errorCode":0},{"partition":365,"offset":"-1","metadata":"","errorCode":0},{"partition":366,"offset":"-1","metadata":"","errorCode":0},{"partition":367,"offset":"-1","metadata":"","errorCode":0},{"partition":368,"offset":"-1","metadata":"","errorCode":0},{"partition":369,"offset":"-1","metadata":"","errorCode":0},{"partition":370,"offset":"-1","metadata":"","errorCode":0},{"partition":371,"offset":"-1","metadata":"","errorCode":0},{"partition":372,"offset":"-1","metadata":"","errorCode":0},{"partition":373,"offset":"-1","metadata":"","errorCode":0},{"partition":374,"offset":"-1","metadata":"","errorCode":0},{"partition":375,"offset":"-1","metadata":"","errorCode":0},{"partition":376,"offset":"-1","metadata":"","errorCode":0},{"partition":377,"offset":"-1","metadata":"","errorCode":0},{"partition":378,"offset":"-1","metadata":"","errorCode":0},{"partition":379,"offset":"-1","metadata":"","errorCode":0},{"partition":380,"offset":"-1","metadata":"","errorCode":0},{"partition":381,"offset":"-1","metadata":"","errorCode":0},{"partition":382,"offset":"-1","metadata":"","errorCode":0},{"partition":383,"offset":"-1","metadata":"","errorCode":0},{"partition":384,"offset":"-1","metadata":"","errorCode":0},{"partition":385,"offset":"-1","metadata":"","errorCode":0},{"partition":386,"offset":"-1","metadata":"","errorCode":0},{"partition":387,"offset":"-1","metadata":"","errorCode":0},{"partition":388,"offset":"-1","metadata":"","errorCode":0},{"partition":389,"offset":"-1","metadata":"","errorCode":0},{"partition":390,"offset":"-1","metadata":"","errorCode":0},{"partition":391,"offset":"-1","metadata":"","errorCode":0},{"partition":392,"offset":"-1","metadata":"","errorCode":0},{"partition":393,"offset":"-1","metadata":"","errorCode":0},{"partition":394,"offset":"-1","metadata":"","errorCode":0},{"partition":395,"offset":"-1","metadata":"","errorCode":0},{"partition":396,"offset":"-1","metadata":"","errorCode":0},{"partition":397,"offset":"-1","metadata":"","errorCode":0},{"partition":398,"offset":"-1","metadata":"","errorCode":0},{"partition":399,"offset":"-1","metadata":"","errorCode":0}]}],"errorCode":0}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.707Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka3:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.707Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka5:9092","clientId":"kafka-reader-local","ssl":false,"sasl":false}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.744Z","logger":"kafkajs","message":"[Connection] Request ListOffsets(key: 2, version: 0)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":4,"size":1353}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.744Z","logger":"kafkajs","message":"[Connection] Request ListOffsets(key: 2, version: 0)","broker":"kafka2.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":1353}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.744Z","logger":"kafkajs","message":"[Connection] Request ListOffsets(key: 2, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":3,"size":1353}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.986Z","logger":"kafkajs","message":"[Connection] Request ListOffsets(key: 2, version: 0)","broker":"kafka5:9092","clientId":"kafka-reader-local","correlationId":0,"size":1353}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.987Z","logger":"kafkajs","message":"[Connection] Request ListOffsets(key: 2, version: 0)","broker":"kafka3:9092","clientId":"kafka-reader-local","correlationId":0,"size":1353}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.989Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 0)","broker":"kafka2.com:9092","clientId":"kafka-reader-local","correlationId":1,"size":1469,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":256,"errorCode":0,"offsets":["4336326"]},{"partition":1,"errorCode":0,"offsets":["4575845"]},{"partition":386,"errorCode":0,"offsets":["4595859"]},{"partition":131,"errorCode":0,"offsets":["4234465"]},{"partition":261,"errorCode":0,"offsets":["4000959"]},{"partition":6,"errorCode":0,"offsets":["3993151"]},{"partition":391,"errorCode":0,"offsets":["4520894"]},{"partition":136,"errorCode":0,"offsets":["4347130"]},{"partition":266,"errorCode":0,"offsets":["3982047"]},{"partition":11,"errorCode":0,"offsets":["4071266"]},{"partition":396,"errorCode":0,"offsets":["4400675"]},{"partition":141,"errorCode":0,"offsets":["4224344"]},{"partition":271,"errorCode":0,"offsets":["4107313"]},{"partition":16,"errorCode":0,"offsets":["4227510"]},{"partition":146,"errorCode":0,"offsets":["4510979"]},{"partition":276,"errorCode":0,"offsets":["4377405"]},{"partition":21,"errorCode":0,"offsets":["4143687"]},{"partition":151,"errorCode":0,"offsets":["4383277"]},{"partition":281,"errorCode":0,"offsets":["4055635"]},{"partition":26,"errorCode":0,"offsets":["4046128"]},{"partition":156,"errorCode":0,"offsets":["4340367"]},{"partition":286,"errorCode":0,"offsets":["4282329"]},{"partition":31,"errorCode":0,"offsets":["4338360"]},{"partition":161,"errorCode":0,"offsets":["4464962"]},{"partition":291,"errorCode":0,"offsets":["4320545"]},{"partition":36,"errorCode":0,"offsets":["4250577"]},{"partition":166,"errorCode":0,"offsets":["4089992"]},{"partition":296,"errorCode":0,"offsets":["4207685"]},{"partition":41,"errorCode":0,"offsets":["4032472"]},{"partition":171,"errorCode":0,"offsets":["3967167"]},{"partition":301,"errorCode":0,"offsets":["4443184"]},{"partition":46,"errorCode":0,"offsets":["4278832"]},{"partition":176,"errorCode":0,"offsets":["4486274"]},{"partition":306,"errorCode":0,"offsets":["4383987"]},{"partition":51,"errorCode":0,"offsets":["4363073"]},{"partition":181,"errorCode":0,"offsets":["4239669"]},{"partition":311,"errorCode":0,"offsets":["4436990"]},{"partition":56,"errorCode":0,"offsets":["4427132"]},{"partition":186,"errorCode":0,"offsets":["4053567"]},{"partition":316,"errorCode":0,"offsets":["4424777"]},{"partition":61,"errorCode":0,"offsets":["4431849"]},{"partition":191,"errorCode":0,"offsets":["4047180"]},{"partition":321,"errorCode":0,"offsets":["4224112"]},{"partition":66,"errorCode":0,"offsets":["4407627"]},{"partition":196,"errorCode":0,"offsets":["4175674"]},{"partition":326,"errorCode":0,"offsets":["4538981"]},{"partition":71,"errorCode":0,"offsets":["4247355"]},{"partition":201,"errorCode":0,"offsets":["4039524"]},{"partition":331,"errorCode":0,"offsets":["4042502"]},{"partition":76,"errorCode":0,"offsets":["4391929"]},{"partition":206,"errorCode":0,"offsets":["4188727"]},{"partition":336,"errorCode":0,"offsets":["4177007"]},{"partition":81,"errorCode":0,"offsets":["4254889"]},{"partition":211,"errorCode":0,"offsets":["4433047"]},{"partition":341,"errorCode":0,"offsets":["4231019"]},{"partition":86,"errorCode":0,"offsets":["4011801"]},{"partition":216,"errorCode":0,"offsets":["4243280"]},{"partition":346,"errorCode":0,"offsets":["4041826"]},{"partition":91,"errorCode":0,"offsets":["3975038"]},{"partition":221,"errorCode":0,"offsets":["4214068"]},{"partition":351,"errorCode":0,"offsets":["4078394"]},{"partition":96,"errorCode":0,"offsets":["4343807"]},{"partition":226,"errorCode":0,"offsets":["4401077"]},{"partition":356,"errorCode":0,"offsets":["4303458"]},{"partition":101,"errorCode":0,"offsets":["4284959"]},{"partition":231,"errorCode":0,"offsets":["4244255"]},{"partition":361,"errorCode":0,"offsets":["4230835"]},{"partition":106,"errorCode":0,"offsets":["4304414"]},{"partition":236,"errorCode":0,"offsets":["4613333"]},{"partition":366,"errorCode":0,"offsets":["4258711"]},{"partition":111,"errorCode":0,"offsets":["4274049"]},{"partition":241,"errorCode":0,"offsets":["4383143"]},{"partition":371,"errorCode":0,"offsets":["4174191"]},{"partition":116,"errorCode":0,"offsets":["4131134"]},{"partition":246,"errorCode":0,"offsets":["4029902"]},{"partition":376,"errorCode":0,"offsets":["4311169"]},{"partition":121,"errorCode":0,"offsets":["4201565"]},{"partition":251,"errorCode":0,"offsets":["3958566"]},{"partition":381,"errorCode":0,"offsets":["4248045"]},{"partition":126,"errorCode":0,"offsets":["4465139"]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.993Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 0)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":3,"size":1469,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":128,"errorCode":0,"offsets":["4159502"]},{"partition":258,"errorCode":0,"offsets":["4313296"]},{"partition":3,"errorCode":0,"offsets":["4266372"]},{"partition":388,"errorCode":0,"offsets":["4389581"]},{"partition":133,"errorCode":0,"offsets":["4606328"]},{"partition":263,"errorCode":0,"offsets":["4115578"]},{"partition":8,"errorCode":0,"offsets":["3933298"]},{"partition":393,"errorCode":0,"offsets":["4483464"]},{"partition":138,"errorCode":0,"offsets":["4264724"]},{"partition":268,"errorCode":0,"offsets":["4307634"]},{"partition":13,"errorCode":0,"offsets":["4203180"]},{"partition":398,"errorCode":0,"offsets":["4439710"]},{"partition":143,"errorCode":0,"offsets":["4295705"]},{"partition":273,"errorCode":0,"offsets":["4088363"]},{"partition":18,"errorCode":0,"offsets":["5070434"]},{"partition":148,"errorCode":0,"offsets":["4308769"]},{"partition":278,"errorCode":0,"offsets":["4270309"]},{"partition":23,"errorCode":0,"offsets":["4157934"]},{"partition":153,"errorCode":0,"offsets":["4450630"]},{"partition":283,"errorCode":0,"offsets":["4065159"]},{"partition":28,"errorCode":0,"offsets":["4294699"]},{"partition":158,"errorCode":0,"offsets":["4495270"]},{"partition":288,"errorCode":0,"offsets":["4321509"]},{"partition":33,"errorCode":0,"offsets":["4089291"]},{"partition":163,"errorCode":0,"offsets":["4279122"]},{"partition":293,"errorCode":0,"offsets":["4301002"]},{"partition":38,"errorCode":0,"offsets":["4256456"]},{"partition":168,"errorCode":0,"offsets":["4145941"]},{"partition":298,"errorCode":0,"offsets":["4240907"]},{"partition":43,"errorCode":0,"offsets":["4063249"]},{"partition":173,"errorCode":0,"offsets":["4347205"]},{"partition":303,"errorCode":0,"offsets":["4969785"]},{"partition":48,"errorCode":0,"offsets":["4382062"]},{"partition":178,"errorCode":0,"offsets":["4351741"]},{"partition":308,"errorCode":0,"offsets":["4134119"]},{"partition":53,"errorCode":0,"offsets":["4341921"]},{"partition":183,"errorCode":0,"offsets":["4319055"]},{"partition":313,"errorCode":0,"offsets":["4955471"]},{"partition":58,"errorCode":0,"offsets":["4392554"]},{"partition":188,"errorCode":0,"offsets":["4093536"]},{"partition":318,"errorCode":0,"offsets":["4437321"]},{"partition":63,"errorCode":0,"offsets":["4384012"]},{"partition":193,"errorCode":0,"offsets":["4048571"]},{"partition":323,"errorCode":0,"offsets":["4072942"]},{"partition":68,"errorCode":0,"offsets":["4204163"]},{"partition":198,"errorCode":0,"offsets":["4044566"]},{"partition":328,"errorCode":0,"offsets":["4084817"]},{"partition":73,"errorCode":0,"offsets":["4292300"]},{"partition":203,"errorCode":0,"offsets":["4025307"]},{"partition":333,"errorCode":0,"offsets":["4150200"]},{"partition":78,"errorCode":0,"offsets":["4477300"]},{"partition":208,"errorCode":0,"offsets":["4137325"]},{"partition":338,"errorCode":0,"offsets":["4393050"]},{"partition":83,"errorCode":0,"offsets":["4110585"]},{"partition":213,"errorCode":0,"offsets":["4568503"]},{"partition":343,"errorCode":0,"offsets":["4266901"]},{"partition":88,"errorCode":0,"offsets":["3945608"]},{"partition":218,"errorCode":0,"offsets":["4201661"]},{"partition":348,"errorCode":0,"offsets":["4101746"]},{"partition":93,"errorCode":0,"offsets":["4707550"]},{"partition":223,"errorCode":0,"offsets":["4332050"]},{"partition":353,"errorCode":0,"offsets":["4071425"]},{"partition":98,"errorCode":0,"offsets":["4529737"]},{"partition":228,"errorCode":0,"offsets":["4772671"]},{"partition":358,"errorCode":0,"offsets":["4308346"]},{"partition":103,"errorCode":0,"offsets":["4780670"]},{"partition":233,"errorCode":0,"offsets":["4276206"]},{"partition":363,"errorCode":0,"offsets":["4321400"]},{"partition":108,"errorCode":0,"offsets":["4131263"]},{"partition":238,"errorCode":0,"offsets":["4658646"]},{"partition":368,"errorCode":0,"offsets":["4161396"]},{"partition":113,"errorCode":0,"offsets":["4094228"]},{"partition":243,"errorCode":0,"offsets":["4271035"]},{"partition":373,"errorCode":0,"offsets":["4550652"]},{"partition":118,"errorCode":0,"offsets":["4232724"]},{"partition":248,"errorCode":0,"offsets":["3914345"]},{"partition":378,"errorCode":0,"offsets":["4177442"]},{"partition":123,"errorCode":0,"offsets":["4118429"]},{"partition":253,"errorCode":0,"offsets":["4194538"]},{"partition":383,"errorCode":0,"offsets":["4380458"]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:16.994Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 0)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":4,"size":1469,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":0,"errorCode":0,"offsets":["4171052"]},{"partition":385,"errorCode":0,"offsets":["4396589"]},{"partition":130,"errorCode":0,"offsets":["4451461"]},{"partition":260,"errorCode":0,"offsets":["4663828"]},{"partition":5,"errorCode":0,"offsets":["4271343"]},{"partition":390,"errorCode":0,"offsets":["4376403"]},{"partition":135,"errorCode":0,"offsets":["4487174"]},{"partition":265,"errorCode":0,"offsets":["4073790"]},{"partition":10,"errorCode":0,"offsets":["4097729"]},{"partition":395,"errorCode":0,"offsets":["4409890"]},{"partition":140,"errorCode":0,"offsets":["4352986"]},{"partition":270,"errorCode":0,"offsets":["4402000"]},{"partition":15,"errorCode":0,"offsets":["4405222"]},{"partition":145,"errorCode":0,"offsets":["4628681"]},{"partition":275,"errorCode":0,"offsets":["4262659"]},{"partition":20,"errorCode":0,"offsets":["4307600"]},{"partition":150,"errorCode":0,"offsets":["4288949"]},{"partition":280,"errorCode":0,"offsets":["4072229"]},{"partition":25,"errorCode":0,"offsets":["4041205"]},{"partition":155,"errorCode":0,"offsets":["4370880"]},{"partition":285,"errorCode":0,"offsets":["4233684"]},{"partition":30,"errorCode":0,"offsets":["4393956"]},{"partition":160,"errorCode":0,"offsets":["4217128"]},{"partition":290,"errorCode":0,"offsets":["4670313"]},{"partition":35,"errorCode":0,"offsets":["4226177"]},{"partition":165,"errorCode":0,"offsets":["4084795"]},{"partition":295,"errorCode":0,"offsets":["4323451"]},{"partition":40,"errorCode":0,"offsets":["3967962"]},{"partition":170,"errorCode":0,"offsets":["4660722"]},{"partition":300,"errorCode":0,"offsets":["4384708"]},{"partition":45,"errorCode":0,"offsets":["4713727"]},{"partition":175,"errorCode":0,"offsets":["4107925"]},{"partition":305,"errorCode":0,"offsets":["4314108"]},{"partition":50,"errorCode":0,"offsets":["5170337"]},{"partition":180,"errorCode":0,"offsets":["4091929"]},{"partition":310,"errorCode":0,"offsets":["4202056"]},{"partition":55,"errorCode":0,"offsets":["4316254"]},{"partition":185,"errorCode":0,"offsets":["4092729"]},{"partition":315,"errorCode":0,"offsets":["4681260"]},{"partition":60,"errorCode":0,"offsets":["4197606"]},{"partition":190,"errorCode":0,"offsets":["4380798"]},{"partition":320,"errorCode":0,"offsets":["4102782"]},{"partition":65,"errorCode":0,"offsets":["4341969"]},{"partition":195,"errorCode":0,"offsets":["4220788"]},{"partition":325,"errorCode":0,"offsets":["4070615"]},{"partition":70,"errorCode":0,"offsets":["4263275"]},{"partition":200,"errorCode":0,"offsets":["4451331"]},{"partition":330,"errorCode":0,"offsets":["4248457"]},{"partition":75,"errorCode":0,"offsets":["4587435"]},{"partition":205,"errorCode":0,"offsets":["4247308"]},{"partition":335,"errorCode":0,"offsets":["4118292"]},{"partition":80,"errorCode":0,"offsets":["4158298"]},{"partition":210,"errorCode":0,"offsets":["4479680"]},{"partition":340,"errorCode":0,"offsets":["4075816"]},{"partition":85,"errorCode":0,"offsets":["4216105"]},{"partition":215,"errorCode":0,"offsets":["4299640"]},{"partition":345,"errorCode":0,"offsets":["4110097"]},{"partition":90,"errorCode":0,"offsets":["4244981"]},{"partition":220,"errorCode":0,"offsets":["4198566"]},{"partition":350,"errorCode":0,"offsets":["4375640"]},{"partition":95,"errorCode":0,"offsets":["4227658"]},{"partition":225,"errorCode":0,"offsets":["4382414"]},{"partition":355,"errorCode":0,"offsets":["4371257"]},{"partition":100,"errorCode":0,"offsets":["4332811"]},{"partition":230,"errorCode":0,"offsets":["4347691"]},{"partition":360,"errorCode":0,"offsets":["4014045"]},{"partition":105,"errorCode":0,"offsets":["4128074"]},{"partition":235,"errorCode":0,"offsets":["4361142"]},{"partition":365,"errorCode":0,"offsets":["4214643"]},{"partition":110,"errorCode":0,"offsets":["4385691"]},{"partition":240,"errorCode":0,"offsets":["4097146"]},{"partition":370,"errorCode":0,"offsets":["4482463"]},{"partition":115,"errorCode":0,"offsets":["4209019"]},{"partition":245,"errorCode":0,"offsets":["4071456"]},{"partition":375,"errorCode":0,"offsets":["4308766"]},{"partition":120,"errorCode":0,"offsets":["4182536"]},{"partition":250,"errorCode":0,"offsets":["4330023"]},{"partition":380,"errorCode":0,"offsets":["4702244"]},{"partition":125,"errorCode":0,"offsets":["4129871"]},{"partition":255,"errorCode":0,"offsets":["4687853"]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.233Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 0)","broker":"kafka3:9092","clientId":"kafka-reader-local","correlationId":0,"size":1469,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":257,"errorCode":0,"offsets":["4075787"]},{"partition":2,"errorCode":0,"offsets":["4270406"]},{"partition":387,"errorCode":0,"offsets":["4396736"]},{"partition":132,"errorCode":0,"offsets":["4359649"]},{"partition":262,"errorCode":0,"offsets":["4037388"]},{"partition":7,"errorCode":0,"offsets":["4199401"]},{"partition":392,"errorCode":0,"offsets":["4510069"]},{"partition":137,"errorCode":0,"offsets":["4255837"]},{"partition":267,"errorCode":0,"offsets":["4285437"]},{"partition":12,"errorCode":0,"offsets":["4351439"]},{"partition":397,"errorCode":0,"offsets":["4309969"]},{"partition":142,"errorCode":0,"offsets":["4433920"]},{"partition":272,"errorCode":0,"offsets":["4367107"]},{"partition":17,"errorCode":0,"offsets":["4347300"]},{"partition":147,"errorCode":0,"offsets":["4470117"]},{"partition":277,"errorCode":0,"offsets":["3938076"]},{"partition":22,"errorCode":0,"offsets":["4100787"]},{"partition":152,"errorCode":0,"offsets":["4239780"]},{"partition":282,"errorCode":0,"offsets":["4263858"]},{"partition":27,"errorCode":0,"offsets":["4238049"]},{"partition":157,"errorCode":0,"offsets":["4391776"]},{"partition":287,"errorCode":0,"offsets":["4339584"]},{"partition":32,"errorCode":0,"offsets":["4188686"]},{"partition":162,"errorCode":0,"offsets":["4299035"]},{"partition":292,"errorCode":0,"offsets":["4273225"]},{"partition":37,"errorCode":0,"offsets":["3991310"]},{"partition":167,"errorCode":0,"offsets":["4057007"]},{"partition":297,"errorCode":0,"offsets":["4180334"]},{"partition":42,"errorCode":0,"offsets":["4063587"]},{"partition":172,"errorCode":0,"offsets":["4149410"]},{"partition":302,"errorCode":0,"offsets":["4654852"]},{"partition":47,"errorCode":0,"offsets":["4564008"]},{"partition":177,"errorCode":0,"offsets":["4053602"]},{"partition":307,"errorCode":0,"offsets":["4289376"]},{"partition":52,"errorCode":0,"offsets":["4317997"]},{"partition":182,"errorCode":0,"offsets":["4075007"]},{"partition":312,"errorCode":0,"offsets":["4349411"]},{"partition":57,"errorCode":0,"offsets":["4405494"]},{"partition":187,"errorCode":0,"offsets":["4320497"]},{"partition":317,"errorCode":0,"offsets":["4340591"]},{"partition":62,"errorCode":0,"offsets":["4599427"]},{"partition":192,"errorCode":0,"offsets":["4676003"]},{"partition":322,"errorCode":0,"offsets":["4355121"]},{"partition":67,"errorCode":0,"offsets":["4317483"]},{"partition":197,"errorCode":0,"offsets":["4196761"]},{"partition":327,"errorCode":0,"offsets":["4008451"]},{"partition":72,"errorCode":0,"offsets":["4278044"]},{"partition":202,"errorCode":0,"offsets":["4043315"]},{"partition":332,"errorCode":0,"offsets":["4148283"]},{"partition":77,"errorCode":0,"offsets":["4411293"]},{"partition":207,"errorCode":0,"offsets":["4429852"]},{"partition":337,"errorCode":0,"offsets":["4089582"]},{"partition":82,"errorCode":0,"offsets":["4475225"]},{"partition":212,"errorCode":0,"offsets":["4323311"]},{"partition":342,"errorCode":0,"offsets":["4032148"]},{"partition":87,"errorCode":0,"offsets":["4186931"]},{"partition":217,"errorCode":0,"offsets":["4389434"]},{"partition":347,"errorCode":0,"offsets":["4005861"]},{"partition":92,"errorCode":0,"offsets":["4285061"]},{"partition":222,"errorCode":0,"offsets":["4325745"]},{"partition":352,"errorCode":0,"offsets":["4275610"]},{"partition":97,"errorCode":0,"offsets":["4146766"]},{"partition":227,"errorCode":0,"offsets":["4528775"]},{"partition":357,"errorCode":0,"offsets":["3988333"]},{"partition":102,"errorCode":0,"offsets":["4107230"]},{"partition":232,"errorCode":0,"offsets":["4539939"]},{"partition":362,"errorCode":0,"offsets":["4206521"]},{"partition":107,"errorCode":0,"offsets":["4134606"]},{"partition":237,"errorCode":0,"offsets":["4157440"]},{"partition":367,"errorCode":0,"offsets":["4508540"]},{"partition":112,"errorCode":0,"offsets":["4223532"]},{"partition":242,"errorCode":0,"offsets":["4361460"]},{"partition":372,"errorCode":0,"offsets":["4337409"]},{"partition":117,"errorCode":0,"offsets":["3998980"]},{"partition":247,"errorCode":0,"offsets":["4024861"]},{"partition":377,"errorCode":0,"offsets":["4236914"]},{"partition":122,"errorCode":0,"offsets":["4107349"]},{"partition":252,"errorCode":0,"offsets":["4143627"]},{"partition":382,"errorCode":0,"offsets":["4487269"]},{"partition":127,"errorCode":0,"offsets":["4256513"]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.251Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 0)","broker":"kafka5:9092","clientId":"kafka-reader-local","correlationId":0,"size":1469,"data":{"responses":[{"topic":"topic1","partitions":[{"partition":384,"errorCode":0,"offsets":["4509043"]},{"partition":129,"errorCode":0,"offsets":["4931843"]},{"partition":259,"errorCode":0,"offsets":["4174938"]},{"partition":4,"errorCode":0,"offsets":["4125294"]},{"partition":389,"errorCode":0,"offsets":["4542018"]},{"partition":134,"errorCode":0,"offsets":["4626219"]},{"partition":264,"errorCode":0,"offsets":["4454568"]},{"partition":9,"errorCode":0,"offsets":["4326602"]},{"partition":394,"errorCode":0,"offsets":["4335358"]},{"partition":139,"errorCode":0,"offsets":["4490645"]},{"partition":269,"errorCode":0,"offsets":["3991245"]},{"partition":14,"errorCode":0,"offsets":["4479916"]},{"partition":399,"errorCode":0,"offsets":["4662815"]},{"partition":144,"errorCode":0,"offsets":["4340794"]},{"partition":274,"errorCode":0,"offsets":["4392174"]},{"partition":19,"errorCode":0,"offsets":["4084740"]},{"partition":149,"errorCode":0,"offsets":["4356976"]},{"partition":279,"errorCode":0,"offsets":["4391175"]},{"partition":24,"errorCode":0,"offsets":["4269890"]},{"partition":154,"errorCode":0,"offsets":["4317495"]},{"partition":284,"errorCode":0,"offsets":["4150334"]},{"partition":29,"errorCode":0,"offsets":["4426378"]},{"partition":159,"errorCode":0,"offsets":["4610794"]},{"partition":289,"errorCode":0,"offsets":["4705146"]},{"partition":34,"errorCode":0,"offsets":["4247502"]},{"partition":164,"errorCode":0,"offsets":["4813232"]},{"partition":294,"errorCode":0,"offsets":["4570931"]},{"partition":39,"errorCode":0,"offsets":["4212255"]},{"partition":169,"errorCode":0,"offsets":["4134412"]},{"partition":299,"errorCode":0,"offsets":["4562000"]},{"partition":44,"errorCode":0,"offsets":["4155126"]},{"partition":174,"errorCode":0,"offsets":["4244166"]},{"partition":304,"errorCode":0,"offsets":["4247565"]},{"partition":49,"errorCode":0,"offsets":["4722240"]},{"partition":179,"errorCode":0,"offsets":["4228956"]},{"partition":309,"errorCode":0,"offsets":["4376540"]},{"partition":54,"errorCode":0,"offsets":["4389621"]},{"partition":184,"errorCode":0,"offsets":["5044757"]},{"partition":314,"errorCode":0,"offsets":["4646111"]},{"partition":59,"errorCode":0,"offsets":["4412647"]},{"partition":189,"errorCode":0,"offsets":["4038252"]},{"partition":319,"errorCode":0,"offsets":["4653495"]},{"partition":64,"errorCode":0,"offsets":["4502702"]},{"partition":194,"errorCode":0,"offsets":["4460015"]},{"partition":324,"errorCode":0,"offsets":["4104755"]},{"partition":69,"errorCode":0,"offsets":["4384186"]},{"partition":199,"errorCode":0,"offsets":["4295902"]},{"partition":329,"errorCode":0,"offsets":["4600018"]},{"partition":74,"errorCode":0,"offsets":["4493816"]},{"partition":204,"errorCode":0,"offsets":["4315768"]},{"partition":334,"errorCode":0,"offsets":["4221895"]},{"partition":79,"errorCode":0,"offsets":["4908099"]},{"partition":209,"errorCode":0,"offsets":["4648739"]},{"partition":339,"errorCode":0,"offsets":["4122164"]},{"partition":84,"errorCode":0,"offsets":["4207168"]},{"partition":214,"errorCode":0,"offsets":["4300882"]},{"partition":344,"errorCode":0,"offsets":["4265487"]},{"partition":89,"errorCode":0,"offsets":["4212298"]},{"partition":219,"errorCode":0,"offsets":["4410491"]},{"partition":349,"errorCode":0,"offsets":["3957568"]},{"partition":94,"errorCode":0,"offsets":["4283925"]},{"partition":224,"errorCode":0,"offsets":["4257961"]},{"partition":354,"errorCode":0,"offsets":["4257955"]},{"partition":99,"errorCode":0,"offsets":["4227447"]},{"partition":229,"errorCode":0,"offsets":["4879475"]},{"partition":359,"errorCode":0,"offsets":["4285847"]},{"partition":104,"errorCode":0,"offsets":["4327992"]},{"partition":234,"errorCode":0,"offsets":["4325750"]},{"partition":364,"errorCode":0,"offsets":["4101234"]},{"partition":109,"errorCode":0,"offsets":["4182627"]},{"partition":239,"errorCode":0,"offsets":["4421362"]},{"partition":369,"errorCode":0,"offsets":["4437728"]},{"partition":114,"errorCode":0,"offsets":["4317960"]},{"partition":244,"errorCode":0,"offsets":["4303076"]},{"partition":374,"errorCode":0,"offsets":["5018868"]},{"partition":119,"errorCode":0,"offsets":["4196332"]},{"partition":249,"errorCode":0,"offsets":["4218264"]},{"partition":379,"errorCode":0,"offsets":["4842829"]},{"partition":124,"errorCode":0,"offsets":["4285949"]},{"partition":254,"errorCode":0,"offsets":["4217568"]}]}]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.255Z","logger":"kafkajs","message":"[ConsumerGroup] Fetching from 1 out of 1 topics","topics":["topic1"],"activeTopics":["topic1"],"pausedTopics":[]}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.325Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"kafka1.com:9092","clientId":"kafka-reader-local","correlationId":5,"size":1366}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.325Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"kafka2.com:9092","clientId":"kafka-reader-local","correlationId":2,"size":1366}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.325Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"kafka3:9092","clientId":"kafka-reader-local","correlationId":1,"size":1366}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.325Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"kafka4.com:9092","clientId":"kafka-reader-local","correlationId":4,"size":1366}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:17.325Z","logger":"kafkajs","message":"[Connection] Request Fetch(key: 1, version: 4)","broker":"kafka5:9092","clientId":"kafka-reader-local","correlationId":1,"size":1366}
{"level":"ERROR","timestamp":"2018-10-08T09:30:19.797Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 4)","broker":"kafka3:9092","clientId":"kafka-reader-local","error":"Invalid magic number: 0 @51637","correlationId":1,"size":1032155}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:19.797Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 4)","broker":"kafka3:9092","clientId":"kafka-reader-local","error":"Invalid magic number: 0 @51637","correlationId":1,"payload":{"type":"Buffer","data":["filtered"]}}
{"level":"DEBUG","timestamp":"2018-10-08T09:30:37.341Z","logger":"kafkajs","message":"[Runner] Error while fetching data, trying again...","groupId":"kafka-reader-local","memberId":"kafka-reader-local-5a42229d-dbb2-46e7-ab5f-47ba89ab98e5","error":"Invalid magic number: 0 @51637","stack":"Error: Invalid magic number: 0 @51637\n    at Decoder.emit_Error (/Users/me/Projects/my-app/service/node_modules/lz4/lib/decoder_stream.js:64:22)\n    at Decoder.read_MagicNumber (/Users/me/Projects/my-app/service/node_modules/lz4/lib/decoder_stream.js:93:8)\n    at Decoder._main (/Users/me/Projects/my-app/service/node_modules/lz4/lib/decoder_stream.js:289:25)\n    at Decoder._transform (/Users/me/Projects/my-app/service/node_modules/lz4/lib/decoder_stream.js:60:7)\n    at Decoder.Transform._read (_stream_transform.js:190:10)\n    at Decoder.Transform._write (_stream_transform.js:178:12)\n    at doWrite (_stream_writable.js:410:12)\n    at writeOrBuffer (_stream_writable.js:394:5)\n    at Decoder.Writable.write (_stream_writable.js:294:11)\n    at Decoder.Writable.end (_stream_writable.js:579:10)","retryCount":0,"retryTime":299}
```

This does not occur on the last tagged release, so I'd appreciate it if you could clue me in on where this could possibly break.

### PR DESCRIPTION
**Pull request by tulios**
Each record batch can contain incomplete records due to how maxBytes works. This should finally fix #152

@paambaati can you try this branch?

Here is a raw FetchV4 Response buffer with an incomplete RecordBatch:
https://drive.google.com/open?id=1gvaudaYIcZWI3GsZNj1ytkbF-QXhGwUo

The file is quite big; the messages are compressed with LZ4

### CODE REVIEW

**Comment by paambaati** [comment]
@tulios I can confirm this works!

**Comment by tulios** [comment]
Awesome! I will merge and release a new version (`1.4.1`)

File: src/protocol/requests/fetch/v4/response.js [hunk 1]
```diff
@@ -41,8 +41,16 @@ const decodeMessages = async decoder => {
     let records = []
 
     while (messagesDecoder.canReadBytes(RECORD_BATCH_OVERHEAD)) {
-      const recordBatch = await RecordBatchDecoder(messagesDecoder)
-      records = [...records, ...recordBatch.records]
+      try {
+        const recordBatch = await RecordBatchDecoder(messagesDecoder)
+        records = [...records, ...recordBatch.records]
+      } catch (e) {
+        // The tail of the record batches can have incomplete records
```
Comment (Nevon) [inline src/protocol/requests/fetch/v4/response.js]: Maybe throw in a reference to https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI and the passage "As an optimization the server is allowed to return a partial message at the end of the message set. Clients should handle this case.", since "due to how maxBytes works" doesn't really tell you much unless you already know what it means.

File: src/protocol/recordBatch/v0/decoder.js [hunk 2]
```diff
@@ -25,7 +26,18 @@ const CONTROL_FLAG_MASK = 0x20
 
 module.exports = async fetchDecoder => {
   const firstOffset = fetchDecoder.readInt64().toString()
-  const decoder = new Decoder(fetchDecoder.readBytes())
+  const length = fetchDecoder.readInt32()
+  const decoder = fetchDecoder.slice(length)
```
Comment (Nevon) [inline src/protocol/recordBatch/v0/decoder.js]: Can't we do this with `Decoder.canReadBytes`?

Comment (Nevon) [reply src/protocol/recordBatch/v0/decoder.js]: That doesn't give `remainingBytes`.

File: src/protocol/requests/fetch/v4/response.js [hunk 3]
```diff
@@ -41,8 +41,16 @@ const decodeMessages = async decoder => {
...
+        // due to how maxBytes works
```
Comment (Nevon) [inline src/protocol/requests/fetch/v4/response.js]:
```suggestion
        // just testing
```

Comment (Nevon) [inline src/protocol/requests/fetch/v4/response.js]:
```suggestion
        // due to how maxBytes works. See https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI
```
