### PR TITLE
Emit GROUP_JOIN event on stale partition assignments

### LINKED ISSUE #923: Adding Partitions Didn't Trigger Group Join Event
**Describe the bug**
We increased the partitions on a topic to meet the demands of incoming traffic. The addition to partitions did not trigger a rebalance for our consumers or producers.

**To Reproduce**

If none of the above are possible to provide, please write down the exact steps to reproduce the behavior:
1. Run a producer that continuously produces messages to a topic
2. Run a consumer that subscribes to that topic and logs each topic offset
3. Send some messages
4. Increase partition count
5. GROUP_JOIN event did not trigger

**Expected behavior**
If the partition count changes, causing a rebalance, then I expect the GROUP_JOIN event would trigger the new partition map. 

**Observed behavior**
The consumer/producer continued as if no changes to partition count change.

**Environment:**
 - KafkaJS version [1.12.0]
 - Kafka version [2.3.1]
 - NodeJS version [12]

### PR DESCRIPTION
**Pull request by Nevon**
Doing this, it occurs to me that `GROUP_JOIN` is not exactly the right name for this event. It's more like `REBALANCED` or `GROUP_STABLE` or something, as it implies that the consumer has not only joined the group but also gone through the synchronization barrier.

Regardless, the join + sync is moved into the consumer group instead of living in the runner, and the `join` and `sync` methods become private so that we don't have the same issue again somewhere else.

Fixes #923

### CODE REVIEW

File: src/consumer/consumerGroup.js [hunk 1]
```diff
@@ -272,6 +283,44 @@ module.exports = class ConsumerGroup {
...
+
+        this.instrumentationEmitter.emit(GROUP_JOIN, payload)
+        this.logger.info('Consumer has joined the group', payload)
+      } catch (e) {
+        if (isRebalancing(e)) {
+          // Rebalance in progress isn't a retriable error since the consumer
+          // has to go through find coordinator and join again before it can
+          // actually retry. Throwing a retriable error to allow the retrier
+          // to keep going
+          throw new KafkaJSError('The group is rebalancing')
```
Comment (ankon) [inline src/consumer/consumerGroup.js:316]: I'm having trouble parsing the comment: "It isn't retriable [...] therefore throw a retriable error".

Comment (Nevon) [reply src/consumer/consumerGroup.js:316]: Heh, yeah, I had the same issue. Took me a bit to figure out what it meant (I just moved it from the runner). Maybe we can come up with a better phrasing.

What it's saying is that the errors that we consider "rebalancing errors" are not retriable errors according to the protocol, but they are operations that we want to handle and retry - so we want the retrier to actually retry, not just bail out. Therefore we turn them into retriable errors even though they technically aren't.

Comment (ankon) [reply src/consumer/consumerGroup.js:316]: > While "rebalance in progress" isn't a retriable error in the protocol [since the consumer ...], we can throw a retriable `KafkaJSError` here to restart that whole sequence using the retrier itself.

Something like that?

Comment (Nevon) [reply src/consumer/consumerGroup.js]: a051f0f hopefully improved it a bit.

Comment (JaapRood) [reply src/consumer/consumerGroup.js]: I understood that last one first try.

**Review by JaapRood — APPROVED** [review]
Haven't ran it, but looks good to me. 

Regarding the naming of `GROUP_JOIN`: you're right that this is more about the rebalance, but more problematic than that is it being an instrument event rather than a first class API on the consumer. If we want to enable exactly-once processing, it's required, as to be able to deal with the sync barrier correctly see [a comment on an related issue ](https://github.com/tulios/kafkajs/issues/592#issuecomment-565063376) and [slack conversation about it](https://kafkajs.slack.com/archives/CF6RFPF6K/p1585645227034200).

None of that should block merging this fix, but something to keep in mind when planning to make changes in that area 🙂.
