### PR TITLE
Handle receiving empty member assignment

### LINKED ISSUE #550: RangeError in consumer group syncGroup response processing for member without assignment
~~~~
 Crash: KafkaJSNumberOfRetriesExceeded: Attempt to access memory outside buffer bounds ({"groupId":"XXXX","retryCount":0,"stack":"KafkaJSNumberOfRetriesExceeded
  Caused by: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at Buffer.readInt16BE (internal/buffer.js:492:5)
    at Decoder.readInt16 (/app/node_modules/kafkajs/src/protocol/decoder.js:36:31)
    at Object.decode (/app/node_modules/kafkajs/src/consumer/assignerProtocol.js:71:24)
    at ConsumerGroup.sync (/app/node_modules/kafkajs/src/consumer/consumerGroup.js:160:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /app/node_modules/kafkajs/src/consumer/runner.js:52:9
    at /app/node_modules/kafkajs/src/consumer/runner.js:354:11"})
~~~~

From my logs it seems that at that point this member didn't receive an assignment, so this piece of code fails:
https://github.com/tulios/kafkajs/blob/34824cbcb2d9721441518ad6875e48f604fd3864/src/consumer/assignerProtocol.js#L71

I think there needs to be a check in any of these places, I'm just not sure which one:
1. Check in ConsumerGroup.sync whether the memberAssignment is empty
2. Check in MemberAssignment.decode whether the given buffer is empty

### PR DESCRIPTION
**Pull request by Nevon**
Fixes #550.

This is a slightly different approach than #551 because I wanted to make sure that the MemberAssignment decoder could handle receiving a buffer with insufficient data, instead of expecting the caller to do the checking for it.

### CODE REVIEW

File: src/consumer/assignerProtocol.js [hunk 1]
```diff
@@ -68,6 +68,10 @@ const MemberAssignment = {
     const indexAssignment = (obj, { topic, partitions }) =>
       Object.assign(obj, { [topic]: partitions })
 
+    if (!decoder.canReadInt16()) {
+      return null
+    }
+
```
Comment (ankon) [inline src/consumer/assignerProtocol.js]: As I mentioned in #551: Doing this does mean that callers need to be changed to be aware of the potential `null` return value. I think it would be good to modify the JSDoc hint then to `@returns {Object|null}` as well.

Comment (Nevon) [reply src/consumer/assignerProtocol.js]: Definitely. Missed that. Fixed in 48eee27

File: types/index.d.ts [hunk 2]
```diff
@@ -338,7 +338,7 @@ export type MemberAssignment = {
 
 export const AssignerProtocol: {
   MemberMetadata: ISerializer<MemberMetadata>
-  MemberAssignment: ISerializer<MemberAssignment>
+  MemberAssignment: ISerializer<MemberAssignment | null>
```
Comment (ankon) [inline types/index.d.ts]: That means MemberAssignment#encode() would need to handle `null` as well now, right?

File: src/consumer/assignerProtocol.js (hunk 1 above)
Comment (JaapRood) [reply src/consumer/assignerProtocol.js]: Whenever I see something returning `null`, I get a little bit weary, especially because of these kinds of consequences. My question would be, how could `MemberAssignment` itself contain the fact that there's no topic-partitions to it's assignment? Technically, the consumer _was_ considered in the rebalance by the leader, and it's assignment just happens to be 0 topic-partitions. If, for example, this return an array of topic-partition pairs, it would simply return an empty array, rather than `null`.

However, with the current structure, I'm not how that was to be represented, and `null` might be the only pragmatic option. Worth discussing at least, I hope.

Comment (Nevon) [reply src/consumer/assignerProtocol.js]: Yeah, that was briefly mentioned in #551, that it would be ideal if `MemberAssignment` could return a sensible value to represent the absence of an assignment. In a different language, I would have had it return something like `Optional<MemberAssignment>`, but we don't have such a construct and the codebase is not structured around encoding non-results as anything but null.

File: types/index.d.ts (hunk 2 above)
Comment (Nevon) [reply types/index.d.ts]: Right! Took me a bit to see what you meant, but yes indeed, it would mean that `encode` would also need to handle receiving null. 

I changed it now so that only the `decode` has a nullable return type.

**Comment by tulios** [comment]
@Nevon can you add an integration test?

File: src/consumer/assignerProtocol.js (hunk 1 above)
Comment (ankon) [reply src/consumer/assignerProtocol.js]: One potential idea could be to introduce a magic constant for "NO_ASSIGNMENT", so at least it becomes obvious what this `null` means ... and of course at that point you don't have to make it null, but rather use an actual value like `{}`.

```typescript
export interface RealMemberAssignment = {
  version: number
  assignment: Assignment
  userData: Buffer
}
export const EMPTY_MEMBER_ASSIGNMENT = {}
export type MemberAssignment = RealMemberAssignment | typeof EMPTY_MEMBER_ASSIGNMENT
export const AssignerProtocol: {
  MemberMetadata: ISerializer<MemberMetadata>
  MemberAssignment: ISerializer<MemberAssignment>
}
```

(Only typed this in Github now, would have to play with that idea a bit and see how the rest of the code feels with that qua readability)

Comment (JaapRood) [reply src/consumer/assignerProtocol.js]: Fair enough!

**Comment by Nevon** [comment]
> @Nevon can you add an integration test?

Done! 9c97aac
